# Generated by Django 3.2.5 on 2021-08-07 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_type', models.CharField(choices=[('SH', 'Shares'), ('CR', 'Crypto')], max_length=2)),
                ('name', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=2)),
                ('platform', models.CharField(max_length=20)),
                ('units_held', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('total_fees', models.FloatField()),
                ('symbol', models.CharField(max_length=5)),
                ('exchange', models.CharField(default='ASX', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.FloatField()),
                ('price', models.FloatField()),
                ('fee', models.FloatField()),
                ('date', models.DateField()),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buffetiser_main.investment')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.FloatField()),
                ('price', models.FloatField()),
                ('fee', models.FloatField()),
                ('date', models.DateField()),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buffetiser_main.investment')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buffetiser_main.investment')),
            ],
        ),
    ]
