# Generated by Django 3.2.5 on 2021-08-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buffetiser_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='currency',
            field=models.CharField(default='AUD', max_length=5),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='platform',
            field=models.CharField(default='CMC', max_length=5),
        ),
    ]
