# Generated by Django 3.2.5 on 2021-10-01 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buffetiser_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='adjustedClose',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investment',
            name='averageCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='investment',
            name='livePrice',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='investment',
            name='percentProfit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='investment',
            name='profit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='investment',
            name='bottomLineValue',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='close',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2021, 10, 1)),
        ),
        migrations.AlterField(
            model_name='history',
            name='high',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='low',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='open',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='investment',
            name='platform',
            field=models.CharField(choices=[('CMC', 'CMC'), ('LINK', 'LINK'), ('BOARDROOM', 'BOARDROOM'), ('DIRECT', 'DIRECT'), ('IPO', 'IPO')], default='CMC', max_length=255),
        ),
    ]
