# Generated by Django 3.2.5 on 2021-08-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buffetiser_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='investment_type',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='investment',
        ),
        migrations.AddField(
            model_name='purchase',
            name='currency',
            field=models.CharField(default='AU', max_length=2),
        ),
        migrations.AddField(
            model_name='purchase',
            name='exchange',
            field=models.CharField(default='ASX', max_length=5),
        ),
        migrations.AddField(
            model_name='purchase',
            name='investment_type',
            field=models.CharField(choices=[('SH', 'Shares'), ('CR', 'Crypto')], default='SH', max_length=2),
        ),
        migrations.AddField(
            model_name='purchase',
            name='name',
            field=models.CharField(default='unnamed', max_length=200),
        ),
        migrations.AddField(
            model_name='purchase',
            name='platform',
            field=models.CharField(default='CMC', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='symbol',
            field=models.CharField(default='none', max_length=5),
        ),
    ]
