# Generated by Django 3.2.5 on 2021-08-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buffetiser_main', '0002_auto_20210824_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='platform',
            field=models.CharField(choices=[('CMC', 'CMC'), ('LINK', 'LINK'), ('BOARDROOM', 'BOARDROOM'), ('DIRECT', 'DIRECT'), ('IPO', 'IPO')], default='CMC', max_length=255),
        ),
    ]
