# Generated by Django 3.2.5 on 2021-08-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buffetiser_main', '0002_auto_20210811_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='id',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='currency',
            field=models.CharField(default='AUD', max_length=2),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='symbol',
            field=models.CharField(default='none', max_length=5, primary_key=True, serialize=False),
        ),
    ]
