# Generated by Django 3.2.5 on 2021-10-04 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buffetiser_main', '0002_auto_20211001_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='bottomLineCost',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='bottomLineValue',
        ),
        migrations.AddField(
            model_name='investment',
            name='plotPath',
            field=models.CharField(default='./', max_length=512),
        ),
        migrations.AddField(
            model_name='investment',
            name='totalCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='investment',
            name='totalValue',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2021, 10, 4)),
        ),
    ]
